language: python
dist: xenial

matrix:
  fast_finish: true
  include:
    - { python: "2.7", env: TOX_ENV=py27-flake8}
    - { python: "2.7", env: TOX_ENV=py27-docs}

    - { python: "2.7", env: DJANGO=1.8 DRF=3.1}
    - { python: "2.7", env: DJANGO=1.8 DRF=3.2}
    - { python: "2.7", env: DJANGO=1.8 DRF=3.3}
    - { python: "2.7", env: DJANGO=1.8 DRF=3.4}
    - { python: "2.7", env: DJANGO=1.8 DRF=3.5}
    - { python: "2.7", env: DJANGO=1.8 DRF=3.6}

    - { python: "2.7", env: DJANGO=1.9 DRF=3.1}
    - { python: "2.7", env: DJANGO=1.9 DRF=3.2}
    - { python: "2.7", env: DJANGO=1.9 DRF=3.3}
    - { python: "2.7", env: DJANGO=1.9 DRF=3.4}
    - { python: "2.7", env: DJANGO=1.9 DRF=3.5}
    - { python: "2.7", env: DJANGO=1.9 DRF=3.6}

    - { python: "2.7", env: DJANGO=1.10 DRF=3.4}
    - { python: "2.7", env: DJANGO=1.10 DRF=3.5}
    - { python: "2.7", env: DJANGO=1.10 DRF=3.6}
    - { python: "2.7", env: DJANGO=1.10 DRF=3.7}
    - { python: "2.7", env: DJANGO=1.10 DRF=3.8}

    - { python: "2.7", env: DJANGO=1.11 DRF=3.4}
    - { python: "2.7", env: DJANGO=1.11 DRF=3.5}
    - { python: "2.7", env: DJANGO=1.11 DRF=3.6}
    - { python: "2.7", env: DJANGO=1.11 DRF=3.7}
    - { python: "2.7", env: DJANGO=1.11 DRF=3.8}
    - { python: "2.7", env: DJANGO=1.11 DRF=3.9}

    - { python: "3.3", env: DJANGO=1.8 DRF=3.1}
    - { python: "3.3", env: DJANGO=1.8 DRF=3.2}
    - { python: "3.3", env: DJANGO=1.8 DRF=3.3}
    - { python: "3.3", env: DJANGO=1.8 DRF=3.4}
    - { python: "3.3", env: DJANGO=1.8 DRF=3.5}
    - { python: "3.3", env: DJANGO=1.8 DRF=3.6}

    - { python: "3.4", env: DJANGO=1.8 DRF=3.1}
    - { python: "3.4", env: DJANGO=1.8 DRF=3.2}
    - { python: "3.4", env: DJANGO=1.8 DRF=3.3}
    - { python: "3.4", env: DJANGO=1.8 DRF=3.4}
    - { python: "3.4", env: DJANGO=1.8 DRF=3.5}
    - { python: "3.4", env: DJANGO=1.8 DRF=3.6}

    - { python: "3.4", env: DJANGO=1.9 DRF=3.1}
    - { python: "3.4", env: DJANGO=1.9 DRF=3.2}
    - { python: "3.4", env: DJANGO=1.9 DRF=3.3}
    - { python: "3.4", env: DJANGO=1.9 DRF=3.4}
    - { python: "3.4", env: DJANGO=1.9 DRF=3.5}
    - { python: "3.4", env: DJANGO=1.9 DRF=3.6}

    - { python: "3.4", env: DJANGO=1.10 DRF=3.4}
    - { python: "3.4", env: DJANGO=1.10 DRF=3.5}
    - { python: "3.4", env: DJANGO=1.10 DRF=3.6}
    - { python: "3.4", env: DJANGO=1.10 DRF=3.7}
    - { python: "3.4", env: DJANGO=1.10 DRF=3.8}

    - { python: "3.4", env: DJANGO=1.11 DRF=3.4}
    - { python: "3.4", env: DJANGO=1.11 DRF=3.5}
    - { python: "3.4", env: DJANGO=1.11 DRF=3.6}
    - { python: "3.4", env: DJANGO=1.11 DRF=3.7}
    - { python: "3.4", env: DJANGO=1.11 DRF=3.8}
    - { python: "3.4", env: DJANGO=1.11 DRF=3.9}

    - { python: "3.4", env: DJANGO=2.0 DRF=3.7}
    - { python: "3.4", env: DJANGO=2.0 DRF=3.8}
    - { python: "3.4", env: DJANGO=2.0 DRF=3.9}

    - { python: "3.5", env: DJANGO=1.11 DRF=3.4}
    - { python: "3.5", env: DJANGO=1.11 DRF=3.5}
    - { python: "3.5", env: DJANGO=1.11 DRF=3.6}
    - { python: "3.5", env: DJANGO=1.11 DRF=3.7}
    - { python: "3.5", env: DJANGO=1.11 DRF=3.8}
    - { python: "3.5", env: DJANGO=1.11 DRF=3.9}

    - { python: "3.5", env: DJANGO=2.0 DRF=3.7}
    - { python: "3.5", env: DJANGO=2.0 DRF=3.8}
    - { python: "3.5", env: DJANGO=2.0 DRF=3.9}

    - { python: "3.5", env: DJANGO=2.1 DRF=3.7}
    - { python: "3.5", env: DJANGO=2.1 DRF=3.8}
    - { python: "3.5", env: DJANGO=2.1 DRF=3.9}

    - { python: "3.6", env: DJANGO=1.11 DRF=3.4}
    - { python: "3.6", env: DJANGO=1.11 DRF=3.5}
    - { python: "3.6", env: DJANGO=1.11 DRF=3.6}
    - { python: "3.6", env: DJANGO=1.11 DRF=3.7}
    - { python: "3.6", env: DJANGO=1.11 DRF=3.8}
    - { python: "3.6", env: DJANGO=1.11 DRF=3.9}

    - { python: "3.6", env: DJANGO=2.0 DRF=3.7}
    - { python: "3.6", env: DJANGO=2.0 DRF=3.8}
    - { python: "3.6", env: DJANGO=2.0 DRF=3.9}

    - { python: "3.6", env: DJANGO=2.1 DRF=3.7}
    - { python: "3.6", env: DJANGO=2.1 DRF=3.8}
    - { python: "3.6", env: DJANGO=2.1 DRF=3.9}

    - { python: "3.7", env: DJANGO=1.11 DRF=3.4}
    - { python: "3.7", env: DJANGO=1.11 DRF=3.5}
    - { python: "3.7", env: DJANGO=1.11 DRF=3.6}
    - { python: "3.7", env: DJANGO=1.11 DRF=3.7}
    - { python: "3.7", env: DJANGO=1.11 DRF=3.8}
    - { python: "3.7", env: DJANGO=1.11 DRF=3.9}

    - { python: "3.7", env: DJANGO=2.0 DRF=3.7}
    - { python: "3.7", env: DJANGO=2.0 DRF=3.8}
    - { python: "3.7", env: DJANGO=2.0 DRF=3.9}

    - { python: "3.7", env: DJANGO=2.1 DRF=3.7}
    - { python: "3.7", env: DJANGO=2.1 DRF=3.8}
    - { python: "3.7", env: DJANGO=2.1 DRF=3.9}

install:
  - pip install tox tox-travis tox-venv

script:
    - tox
